index:
    path: /index
    controller: App\Controller\HomeController::index
admin/login:
    path: admin/login
    controller: App\Controller\AdminLoginController::index
admin/dashboard:
    path: admin/dashboard
    controller: App\Controller\AdminDashboardController::index

admin/cartegory:
    path: admin/cartegory
    controller: App\Controller\CategoryController::index
admin/books:
    path: admin/books
    controller: App\Controller\BooksController::index
    
